name: Greetings #in the workflow it will mention greetings instead of path

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    #https://github.com/actions/first-interaction
    - uses: actions/first-interaction@v1
      with: #is our input how we are inputting things to the action
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
