on:
    schedule:
        -   cron: "*/2 * * * *"

jobs:
   hellow_world:
     runs-on: ubuntu-latest
     steps:
       - name: Echo current exact time 
         run: echo "The current server time as of now is $(date)"